In [2]:
import numpy as np 
from einops import pack, unpack 
h = 2
w = 2
image_rgb = np.random.random([h,w,2])
image_depth = np.random.random([h,w,4])
image_rgb, image_depth

(array([[[0.46058973, 0.96806849],
         [0.02223709, 0.44487335]],
 
        [[0.56060503, 0.45852332],
         [0.30781364, 0.52172878]]]),
 array([[[0.31910063, 0.56173145, 0.05753357, 0.02607512],
         [0.03526205, 0.93310549, 0.30490431, 0.00703838]],
 
        [[0.51389052, 0.69633055, 0.565047  , 0.87000357],
         [0.95635406, 0.3608906 , 0.17336606, 0.29586882]]]))

In [3]:
image_rgbd, ps = pack([image_rgb, image_depth], "h w *")
image_rgbd, ps

(array([[[0.46058973, 0.96806849, 0.31910063, 0.56173145, 0.05753357,
          0.02607512],
         [0.02223709, 0.44487335, 0.03526205, 0.93310549, 0.30490431,
          0.00703838]],
 
        [[0.56060503, 0.45852332, 0.51389052, 0.69633055, 0.565047  ,
          0.87000357],
         [0.30781364, 0.52172878, 0.95635406, 0.3608906 , 0.17336606,
          0.29586882]]]),
 [(2,), (4,)])

In [12]:
import torch
import torch.nn.functional as F
n = torch.tensor([1,2,3]) 
m = torch.tensor([4,5,6])
m = F.normalize(m.double(), dim=-1)
(n * m).sum(dim = -1, keepdim = True) * m 

tensor([1.6623, 2.0779, 2.4935], dtype=torch.float64)

In [13]:
def fn():
    return  4, 5,4

b, *a = fn()
a

[5, 4]